### ISSUE TITLE
push 4.2.1

### ISSUE THREAD

**Issue by jfroom** [videojs/video.js-component#5]
Sorry guys, can we get an update on this repo to 4.2.1? Not sure if there's an more automated way to sync these on releases. Many thanks.

**Comment by jfroom** [comment]
Also, bower.json and package.json versions are out of sync in this repo.

**Comment by dmlap** [comment]
We definitely need to figure out how to automate this better but I've published 4.2.1 in the meantime.

**Comment by gkatsev** [comment]
I have some ideas. We'll see when I get back.

**Comment by heff** [comment]
With all of this I'm becoming more favorable to the idea of just keeping the files in the main repo. The issue around that has been that it can be confusing when you're searching the codebase and people end up making pull requests against the built version (CSS and JS). Also merge conflicts on every pull request because of the built/compiled versions. One thing we could do would be to keep the dist folder ignored and used `git add --force` to make updates to the dist files. When you clone a repo, does it copy down ignored files in the remote repo or ignore them in cloning too? Any thoughts on this?

**Comment by bcjwilson** [comment]
When you clone a repo, you get everything in the repo, including what would be ignored according to the .gitignore file. .gitignore is only consulted when choosing what to `--add` (AFAIK).

**Comment by heff** [comment]
Hmm. We could release, tag, and then immediately remove the compiled files. So the files will be there for the version tag, but not in the clone.

**Comment by gkatsev** [comment]
http://mclear.co.uk/2013/10/06/publishing-to-npm-on-git-commit-using-github-hooks-and-travis/

**Comment by jfroom** [comment]
LoDash has a 'dist' folder and then their bower.json points to that folder, plus a bunch of ignore patterns:
https://github.com/lodash/lodash
https://github.com/lodash/lodash/blob/master/bower.json

**Comment by heff** [comment]
@jfroom That goes back to [the reasons we split it out](https://github.com/videojs/video.js/issues/536). But it could be that dist + gitignore + force pushing dist updates is the better long term solution.

**Comment by gkatsev** [comment]
npm doesn't care what the repo contains which is nice. It just tars up what you have and that's what gets pulled down when you do `npm install`. So, for it, we can just have a `prepublish` script that builds vjs and then the dist folder is available.

Bower, however, does specifically look at the git repo. The good thing is that it relies on git tags, so, we could possibly have the dist folder force checked into the stable branch only.
